### ISSUE TITLE
Update llama to pickup "Avoid heavy V transpose operation + improvements"

### ISSUE THREAD

**Issue by deadprogram** [go-skynet/llama-cli#11]
Please see https://github.com/ggerganov/llama.cpp/pull/775

I added issue in this repo since the https://github.com/go-skynet/llama repo doesn't have issues available.

Thanks! :smile_cat:

**Comment by deadprogram** [comment]
Just discovered https://github.com/go-skynet/go-llama.cpp

Closing since all the action is there.

**Comment by mudler** [comment]
Correct! Seems you already found out all the bits - I will tag soon a new release that should include that as well. Currently images tagged with latest already have the change in, however the API changed quite a bit, mimicking OpenAI api with multi model support (thus docs needs to be updated!)
