### ISSUE TITLE
Feature Request: select model from drop down in ui

### ISSUE THREAD

**Issue by mkellerman** [go-skynet/llama-cli#12]
Since you can now load multiple models, we should provide a drop down in the default web UI, and have the model be passed with each request.

acceptance criteria:
- Not sure if a thread is started with each request, and how this handles multiple parallel requests, but i would make sure to check if a model is already loaded, and use the same if it is, so it doesn't load the same model between each request.
- Match the openai api structure for the requests, so you can pick between models the same way you would with GPT-3.5 or GPT-4, etc.

**Comment by mkellerman** [comment]
match openai api has been implemented. and there is a way to select the model in the Chatbot-UI.. we should get that part done and this story can be closed.

**Comment by mudler** [comment]
closing then in favour of the webui story

**Comment by mudler** [comment]
story: https://github.com/go-skynet/llama-cli/issues/29
