### ISSUE TITLE
Model too old, how do I regenerate?

### ISSUE THREAD

**Issue by jodosha** [go-skynet/llama-cli#8]
Hi, thanks for this project. 😃 

I've got the `.bin` model today I don't remember from where 😅 .

```shell
# docker run -v $PWD/models:/models -p 8080:8080 -ti --rm quay.io/go-skynet/llama-cli api --model /models/ggml-alpaca-7b-q4.bin
llama_model_load: invalid model file '/models/ggml-alpaca-7b-q4.bin' (too old, regenerate your model files!)
llama_bootstrap: failed to load model from '/models/ggml-alpaca-7b-q4.bin'
Loading the model failed: failed loading model
```

How do I regenerate the model?
I tried with the instructions from README (https://github.com/go-skynet/llama-cli#using-other-models), but without success.

**Comment by mudler** [comment]
Hi @jodosha !

Did you tried with the gpt4all instructions too? the model seems before the ggml2 format conversion.

Here it is how I've converted mine:

```
wget -O tokenizer.model https://huggingface.co/decapoda-research/llama-30b-hf/resolve/main/tokenizer.model
mkdir models
cp ggml-alpaca-7b-q4.bin models/
git clone https://gist.github.com/eiz/828bddec6162a023114ce19146cb2b82
pip install sentencepiece
python 828bddec6162a023114ce19146cb2b82/gistfile1.txt models tokenizer.model
# this should generate a models/ggml-alpaca-7b-q4.bin.tmp file
```

What's the error you have?

**Comment by jodosha** [comment]
@mudler Thanks, it works!

You made me realize I should use the `bin.tmp` file instead of the `.bin` one.

The `docker` argument should be:

```diff
- --model /models/ggml-alpaca-7b-q4.bin
+ --model /models/ggml-alpaca-7b-q4.bin.tmp
```
